/* Apaga os relacionamentos */
-- SETOR não tem FKs
ALTER TABLE LABDATABASE.FUNCIONARIO DROP CONSTRAINT SETOR_FUNCIONARIO_FK;
ALTER TABLE LABDATABASE.TAREFA DROP CONSTRAINT FUNCIONARIO_TAREFA_FK;

/* Apaga as tabelas */
DROP TABLE LABDATABASE.TAREFA;
DROP TABLE LABDATABASE.FUNCIONARIO;
DROP TABLE LABDATABASE.SETOR;

/* Apaga as sequences */
DROP SEQUENCE LABDATABASE.SETOR_ID_SEQ;
DROP SEQUENCE LABDATABASE.FUNCIONARIO_MATRICULA_SEQ;
DROP SEQUENCE LABDATABASE.TAREFA_ID_SEQ;

/* Cria as tabelas */
CREATE TABLE LABDATABASE.SETOR (
                ID NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT SETOR_PK PRIMARY KEY (ID)
);

CREATE TABLE LABDATABASE.FUNCIONARIO (
                MATRICULA VARCHAR2(11) NOT NULL, -- CORREÇÃO: Deve ser VARCHAR2
                NOME VARCHAR2(255) NOT NULL,
                ID_SETOR NUMBER NOT NULL,
                CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (MATRICULA)
);

CREATE TABLE LABDATABASE.TAREFA (
                ID NUMBER NOT NULL,
                DESCRICAO VARCHAR2(4000) NOT NULL,
                DATA_LIMITE DATE NOT NULL,
                STATUS VARCHAR2(50) NOT NULL,
                ID_FUNCIONARIO VARCHAR2(11) NOT NULL, -- CORREÇÃO: Deve ser VARCHAR2
                CONSTRAINT TAREFA_PK PRIMARY KEY (ID)
);


/* Cria as sequences */
CREATE SEQUENCE LABDATABASE.SETOR_ID_SEQ;
CREATE SEQUENCE LABDATABASE.FUNCIONARIO_MATRICULA_SEQ;
CREATE SEQUENCE LABDATABASE.TAREFA_ID_SEQ;

/* Cria os relacionamentos */
ALTER TABLE LABDATABASE.FUNCIONARIO ADD CONSTRAINT SETOR_FUNCIONARIO_FK
FOREIGN KEY (ID_SETOR)
REFERENCES LABDATABASE.SETOR (ID)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.TAREFA ADD CONSTRAINT FUNCIONARIO_TAREFA_FK
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES LABDATABASE.FUNCIONARIO (MATRICULA)
NOT DEFERRABLE;

/* Garante acesso total as tabelas */
GRANT ALL ON LABDATABASE.SETOR TO LABDATABASE;
GRANT ALL ON LABDATABASE.FUNCIONARIO TO LABDATABASE;
GRANT ALL ON LABDATABASE.TAREFA TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;