/* INSERE DADOS NA TABELA DE SETOR */
INSERT INTO LABDATABASE.SETOR VALUES(LABDATABASE.SETOR_ID_SEQ.NEXTVAL, 'DESENVOLVIMENTO');
INSERT INTO LABDATABASE.SETOR VALUES(LABDATABASE.SETOR_ID_SEQ.NEXTVAL, 'INFRAESTRUTURA');
INSERT INTO LABDATABASE.SETOR VALUES(LABDATABASE.SETOR_ID_SEQ.NEXTVAL, 'SUPORTE');
INSERT INTO LABDATABASE.SETOR VALUES(LABDATABASE.SETOR_ID_SEQ.NEXTVAL, 'FINANCEIRO');

/* INSERE DADOS NA TABELA DE FUNCIONARIO (usa os IDs de SETOR)*/
DECLARE
  VID_SETOR NUMBER;
BEGIN
  SELECT ID INTO VID_SETOR FROM LABDATABASE.SETOR WHERE NOME = 'DESENVOLVIMENTO';
  INSERT INTO LABDATABASE.FUNCIONARIO VALUES(LABDATABASE.FUNCIONARIO_MATRICULA_SEQ.NEXTVAL, 'ANA PAULA', VID_SETOR);
  
  SELECT ID INTO VID_SETOR FROM LABDATABASE.SETOR WHERE NOME = 'DESENVOLVIMENTO';
  INSERT INTO LABDATABASE.FUNCIONARIO VALUES(LABDATABASE.FUNCIONARIO_MATRICULA_SEQ.NEXTVAL, 'BRUNO SOUZA', VID_SETOR);
  
  SELECT ID INTO VID_SETOR FROM LABDATABASE.SETOR WHERE NOME = 'INFRAESTRUTURA';
  INSERT INTO LABDATABASE.FUNCIONARIO VALUES(LABDATABASE.FUNCIONARIO_MATRICULA_SEQ.NEXTVAL, 'CARLA MELO', VID_SETOR);
  
  SELECT ID INTO VID_SETOR FROM LABDATABASE.SETOR WHERE NOME = 'SUPORTE';
  INSERT INTO LABDATABASE.FUNCIONARIO VALUES(LABDATABASE.FUNCIONARIO_MATRICULA_SEQ.NEXTVAL, 'DANIEL COSTA', VID_SETOR);
  
  SELECT ID INTO VID_SETOR FROM LABDATABASE.SETOR WHERE NOME = 'FINANCEIRO';
  INSERT INTO LABDATABASE.FUNCIONARIO VALUES(LABDATABASE.FUNCIONARIO_MATRICULA_SEQ.NEXTVAL, 'ELIANA GOMES', VID_SETOR);
END;
/
COMMIT;