SELECT
    T.ID AS CODIGO_TAREFA
    , T.DESCRICAO AS TAREFA
    , T.DATA_LIMITE
    , T.STATUS
    , F.NOME AS FUNCIONARIO_RESPONSAVEL
    , S.NOME AS SETOR
FROM
    LABDATABASE.TAREFA T
INNER JOIN
    LABDATABASE.FUNCIONARIO F ON T.ID_FUNCIONARIO = F.MATRICULA
INNER JOIN
    LABDATABASE.SETOR S ON F.ID_SETOR = S.ID
ORDER BY
    T.DATA_LIMITE, F.NOME