SELECT
    F.NOME AS FUNCIONARIO
    , S.NOME AS SETOR
    , T.DESCRICAO AS TAREFA
    , T.STATUS
    , T.DATA_LIMITE
FROM
    LABDATABASE.FUNCIONARIO F
INNER JOIN
    LABDATABASE.SETOR S ON F.ID_SETOR = S.ID
INNER JOIN
    LABDATABASE.TAREFA T ON F.MATRICULA = T.ID_FUNCIONARIO
ORDER BY
    F.NOME, T.DATA_LIMITE